React Project - Calculator , MILESTONE 2
tanzila-abedin/react-calculator pull request #2
Opened 2021-10-13 22:38 UTC by tanzila-abedin

**4 following components  are created to render In APP:**
 
1. Wrapper: Parent component of Display and ButtonPanel.
2. Display: child of wrapper component.
3. ButtonPanel: Parent of Button component
4. Button: Child of ButtonPanel.

- Individual files were created for each component.
- 4 functional components were created.

2021-10-13 23:52 UTC, e71az requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @tanzila-abedin, I am Elias, your reviewer for this PR

Well done so far with your project!

I really liked the clever way that you managed the button rendering, great job so far! You are missing some really small details before moving on, good luck!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [ ] Please check the comments that I left in this PR.

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-10-13 23:52 UTC, e71az commented on src/App.js
> -import logo from './logo.svg';
- [ ] Your App.js file should be placed inside your components folder to comply with the project requirements, please do so 👍

2021-10-13 23:52 UTC, e71az commented on src/App.js
> +// import './App.css';
- [ ] Please remove this and any other commented code that you may have to keep your codebase clean.

2021-10-13 23:52 UTC, e71az commented on src/App.js
>      <div className="App">
- [ ] The React.fragment short syntax should be used to wrap the children components for this function, please do so to comply with the project requirements: Has children components wrapped in [React.Fragment](https://reactjs.org/docs/fragments.html#short-syntax) short syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/app/ReactFragment.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896092/))

2021-10-13 23:52 UTC, e71az commented on src/components/Display.js
> +    {value}
- [ ] its result prop should be a String with default value = 0 (Right now, it is only being initialized with the value 0 but 0 is not set as the default value, you can do so by equaling value to 0 at the function parameter)  ([should be String screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)) ([default props screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png))

2021-10-13 23:52 UTC, e71az commented on src/App.js
> +                console.log(`${btn} clicked!`);
- [ ] Please avoid the use of console.log in code being reviewed, you are free to use it while developing but it should not be present in the pull request, plus this is giving warning errors when running your app, please remove it for something else 👍

2021-10-14 10:22 UTC, george-shammar requested changes
Hi @tanzila-abedin  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-10-14 10:22 UTC, george-shammar commented on src/App.css
> +} */
- [ ] As mentioned by the last reviewer, please clean up commented codes from your codebase. All the codes in this file have been commented out. Please, let's clean it up. :pray: You may delete the file altogether if its not useful.

2021-10-14 11:10 UTC, merged